version: '3.8'

services:
  docs:
    build: .
    ports:
      - "8080:80"
    container_name: kong-docs-offline
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s